apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: acme
spec:
  exportTo:
  - .
  - istio-system
  gateways:
  - acme-gateway
  hosts:
  - "*"
  http:
  - match:
    - headers: 
         User-Agent:
           regex: ".*rome.*"
    route:
    - destination:
        host: v1.shopping.<gns_domain>
        port:
          number: 3000
  - route:
     - destination:
         host: v2.shopping.<gns_domain>
         port:
           number: 3000