apiVersion: gns.tsm.vmware.com/v1
kind: TrafficRoutingPolicy
metadata:
  labels:
    gnsId: rickacme-demo
    projectId: default
  name: shopping-steering-browser
spec:
  description: browser based policy to route traffic
  service: shopping
  traffic_policy:
    http:
    - name: chrome-rule
      matches:
      - headers:
          type: RegularExpression
          value:
          - k: User-Agent
            v: ".*rome.*"
      targets:
      - service_version: v1
    - name: firefox-rule
      matches:
      - headers:
          type: RegularExpression
          value:
          - k: User-Agent
            v: ".*ire.*"
      targets:
      - service_version: v2